// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110222731_Inicial2")]
    partial class Inicial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Adulto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdultoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discapacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdultoId");

                    b.ToTable("adulto");
                });

            modelBuilder.Entity("Domain.Entities.FichaEnfermeria", b =>
                {
                    b.Property<Guid>("CodEnf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdultoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FrecuenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<Guid>("IdAdulto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PesoTalla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresionArterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Pulso")
                        .HasColumnType("real");

                    b.Property<string>("Temperatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodEnf");

                    b.HasIndex("AdultoId");

                    b.ToTable("fichaEnf");
                });

            modelBuilder.Entity("Domain.Entities.FichaFisioterapia", b =>
                {
                    b.Property<Guid>("CodFis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdultoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquiposEmpleados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaProgramacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAdulto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSesiones")
                        .HasColumnType("int");

                    b.HasKey("CodFis");

                    b.HasIndex("AdultoId");

                    b.ToTable("fichaFis");
                });

            modelBuilder.Entity("Domain.Entities.FichaOrientacion", b =>
                {
                    b.Property<Guid>("CodOri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdultoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaOrientacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAdulto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoOrientacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodOri");

                    b.HasIndex("AdultoId");

                    b.ToTable("fichaOri");
                });

            modelBuilder.Entity("Domain.Entities.FichaProteccion", b =>
                {
                    b.Property<Guid>("CodPro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdultoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaProteccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAdulto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoProteccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodPro");

                    b.HasIndex("AdultoId");

                    b.ToTable("fichaPro");
                });

            modelBuilder.Entity("Domain.Entities.Adulto", b =>
                {
                    b.HasOne("Domain.Entities.Adulto", null)
                        .WithMany("Adultos")
                        .HasForeignKey("AdultoId");
                });

            modelBuilder.Entity("Domain.Entities.FichaEnfermeria", b =>
                {
                    b.HasOne("Domain.Entities.Adulto", "Adulto")
                        .WithMany()
                        .HasForeignKey("AdultoId");

                    b.Navigation("Adulto");
                });

            modelBuilder.Entity("Domain.Entities.FichaFisioterapia", b =>
                {
                    b.HasOne("Domain.Entities.Adulto", "Adulto")
                        .WithMany()
                        .HasForeignKey("AdultoId");

                    b.Navigation("Adulto");
                });

            modelBuilder.Entity("Domain.Entities.FichaOrientacion", b =>
                {
                    b.HasOne("Domain.Entities.Adulto", "Adulto")
                        .WithMany()
                        .HasForeignKey("AdultoId");

                    b.Navigation("Adulto");
                });

            modelBuilder.Entity("Domain.Entities.FichaProteccion", b =>
                {
                    b.HasOne("Domain.Entities.Adulto", "Adulto")
                        .WithMany()
                        .HasForeignKey("AdultoId");

                    b.Navigation("Adulto");
                });

            modelBuilder.Entity("Domain.Entities.Adulto", b =>
                {
                    b.Navigation("Adultos");
                });
#pragma warning restore 612, 618
        }
    }
}
